---
title: "Iterations_listcols"
author: "Zheyan"
date: "11/9/2021"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
set.seed(1)
```

## Lists

```{r define a list}
l = list(
  vec_numeric = 5:8,
  mat         = matrix(1:8, 2, 4),
  vec_logical = c(TRUE, FALSE),
  summary     = summary(rnorm(1000)))

l
```

## List of normals



```{r pressure, echo=FALSE}
list_norms = 
  list(a = rnorm(50, mean = 2, sd = 1),
       b = rnorm(50, mean = 5, sd = 2),
       c = rnorm(50, mean = 10, sd = 8),
       d = rnorm(50, mean = 5, sd = 5))

mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}

# put one element, one bracket gives index, two brackets omit index
mean_and_sd(list_norms[[1]])

```

## For loop

Iterate over my list of normals

```{r}
# create empty list
output = vector('list', length = 4)

output[[1]] = mean_and_sd(list_norms[[1]])

for (i in 1:4){
  
  output[[i]] = mean_and_sd(list_norms[[i]])
}

output

```

Write a map instead

```{r}
output = map(list_norms, mean_and_sd)
output = map(list_norms, median)

output = map_dbl(list_norms, median)
```


## List colums

```{r}
listcol_df = 
  tibble(
    name = c('a', 'b', 'c', 'd'),
    norms = list_norms
  )

listcol_df = 
  listcol_df %>% 
    mutate(summarize = map(listcol_df$norms, mean_and_sd))

```



## Nested data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

Nest data with location

```{r}
weather_nested = nest(weather_df, data = date:tmin)

weather_nested %>% 
  pull(data)

lm(tmax ~ tmin, data = weather_nested$data[[3]])

weather_lm = function(df) {
  lm(tmax ~ tmin, data = df)
}

weather_lm(weather_nested$data[[1]])

map(weather_nested$data, weather_lm)
```


## Napoleon



```{r}
read_page_reviews = function(url) {
  
  html = read_html(url)
  
  title = 
    html %>%
    html_nodes("#cm_cr-review_list .review-title") %>%
    html_text()
  
  stars = 
    html %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("\\d") %>%
    as.numeric()
  
  text = 
    html %>%
    html_nodes(".review-data:nth-child(5)") %>%
    html_text()
  
  tibble(title, stars, text)
}
```


We can use this function to read the five pages of reviews on the URLs defined in the code chunk below.

```{r}
url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="
vec_urls = str_c(url_base, 1:5)
```

```{r}
output = vector("list", 5)

for (i in 1:5) {
  output[[i]] = read_page_reviews(vec_urls[[i]])
}

# merge several tibbles

dynamite_reviews = bind_rows(output)

dynamite_reviews = map_df(vec_urls, read_page_reviews)
```






