---
title: "EDA"
author: "Zheyan"
date: "10/12/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Exploratory data analysis

```{r, eval = FALSE}
library(tidyverse)
library(patchwork)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = 'bottom'))

options(
  ggplot2.continuous.colour = 'viridis',
  ggplot2.continuous.fill = 'viridis'
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Read data 

```{r}
weather_df =  
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())
```
## Group by and count something

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarise(avgtmax = mean(tmax))

weather_df %>% 
  group_by(month) %>% 
  summarise(n_obs = n())

weather_df %>% 
  count(name)
```

Output is a dataframe, table does not work

```{r}
weather_df %>% 
  pull(name) %>% 
  table()
```

Give a table for someone else to look at

```{r}
weather_df %>% 
  janitor::tabyl(name, month)
```
# More general summaries

Lets count , take means, look at SDs

```{r}
weather_df %>% 
  group_by(name,month) %>% 
  summarise(
    n_obs = n(),
    mean_tmax = mean(tmax, na.rm = TRUE),
    meidan_tmax = median(tmax, na.rm = TRUE),
    sd_max = sd(tmax, na.rm = TRUE)
  ) %>% 
  ggplot(aes(x = month, y = mean_tmax, color = name))+
  geom_point() + geom_line()
```


## grouped `mutate`

```{r}
weather_df %>% 
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE),
    centered_tmax = tmax - mean_tmax
  ) %>% 
  ggplot(aes(x = date, y = centered_tmax, color = name)) +
  geom_point()
```
# Window Functions

min_rank

```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(
    tmax_rank = min_rank(-tmax)
  ) %>% 
  filter(tmax_rank < 2)
```

Lagged variables

```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(
    lagged_tmax = lag(tmax, n =1)
  )
```











